name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

jobs:
  verify_plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin

    strategy:
      matrix:
        node-version: [10.x]

    steps:   
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}   
      - run: npm i
      - run: npm run build

  verify_examples:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: examples

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  
      - run: npm ci
      - run: npm run update-snapshots
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Snapshots change
          commit_options: '--no-verify --signoff'
          file_pattern: cypress/*
