name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify_plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin

    strategy:
      matrix:
        node-version: [10.x]

    steps:   
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}   
          
      - name: Build plugin
        run: | 
          npm i
          npm run build

  verify_examples:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: examples

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  
        
      
      - name: Build plugin
        working-directory: plugin
        run: |
          npm i
          npm run build

      - name: Verify snapshots
        if: ${{ !contains(github.ref, 'refs/heads/dev/') }}
        run: |
          npm ci
          npm run start-ci --updateSnapshots=false --ignoreSnapshotError=false --snapshotsOs=${{matrix.os}}
      
      - name: Update snapshots
        if: ${{ contains(github.ref, 'refs/heads/dev/') }}
        run: |
          npm ci
          npm run start-ci --updateSnapshots=true --ignoreSnapshotError=true --snapshotsOs=${{matrix.os}}

      - name: Commit snapshots
        run: |
          git pull
          git add examples/cypress/**/*.snap.png
          git commit -m "Snapshots change (${{ matrix.os }})"
          git push

