name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

jobs:
  verify_plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin

    strategy:
      matrix:
        node-version: [10.x]

    steps:   
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}   
          
      - name: Build plugin
        run: | 
          npm i
          npm run build

  verify_examples:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: examples

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  
          
      - name: Build plugin
        working-directory: plugin
        run: |
          npm i
          npm run build

      - name: Verify snapshots
        if: ${{ !contains(github.ref, 'refs/heads/dev/') }}
        run: |
          npm ci
          npm run start-ci --updateSnapshots=false --ignoreSnapshotError=false --snapshotsOs=${{matrix.os}}

  commit_snapshots:
    runs-on: ubuntu_latest
    if: ${{ contains(github.ref, 'refs/heads/dev/') }}
    needs: verify_examples
    defaults:
      run:
        working-directory: examples

    steps: 
      - name: Commit snapshots
      run: |
        git add **/*.snap.png
        git commit -m "Snapshots updated"
        git push
      
