name: Verify

on:
  push:
    branches: [master, dev/*]
  pull_request:
    branches: [master, dev/*] 

jobs:
  start:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          verify: npm run start-ci
